// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

console.log('hello');
document.querySelector('.about-header').addEventListener("click", function(){
  var circle = document.querySelector(".about .circle");
  circle.classList.toggle('resizeCircle');

  var unhide = document.querySelector('.about-content');
  unhide.classList.toggle('hidden');
});
